modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "explosivessquared"
version = "${version}"
displayName = "Explosives Squared"
authors = "Will BL"
description = '''
'''
#logoFile = ""

[[dependencies.explosivessquared]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.explosivessquared]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.explosivessquared]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"